# Generated by Django 3.2 on 2023-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(default=True, upload_to='doctor/'),
        ),
    ]
